### ISSUE TITLE
[BUG] Using parentheses in the class name causes an error in the "tailwindcss/no-custom-classname" rule

### ISSUE THREAD

**Issue by Serator** [francoismassart/eslint-plugin-tailwindcss#100]
**Describe the bug**
I add the class `grid-cols-1fr/minmax(0/360)/1fr` and get an error:
![image](https://user-images.githubusercontent.com/625005/149736282-6ff22f84-902d-4852-9328-a0c18d05ebd7.png)

**Expected behavior**
There should be no error.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Softwares + version used:
     -  VSCode: 1.63.2
     - eslint-plugin-tailwindcss: 3.2.0
     - tailwindcss: 3.0.13

**eslint config file or live demo**
https://play.tailwindcss.com/GohnukdRTq

**Comment by francoismassart** [comment]
Please try

`npm i eslint-plugin-tailwindcss@3.2.1-beta.2`

and provide feedback 😉

**Comment by Serator** [comment]
@francoismassart Yeah, it works for me. 👍
