### ISSUE TITLE
[BUG] Using the percent symbol in square brackets of the class name causes an error in the "tailwindcss/no-custom-classname" rule

### ISSUE THREAD

**Issue by Serator** [francoismassart/eslint-plugin-tailwindcss#101]
**Describe the bug**
I add the class `text-ffffff/[24%]` and get an error:
![image](https://user-images.githubusercontent.com/625005/149738711-f47fc13b-45d2-477f-8390-3ea85f8279a0.png)

**Expected behavior**
There should be no error.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Softwares + version used:
     -  VSCode: 1.63.2
     - eslint-plugin-tailwindcss: 3.2.0
     - tailwindcss: 3.0.13

**eslint config file or live demo**
https://play.tailwindcss.com/AzOrcWBRP4

**Comment by francoismassart** [comment]
Please try

`npm i eslint-plugin-tailwindcss@3.2.1-beta.2`

and provide feedback 😉

**Comment by Serator** [comment]
@francoismassart Yeah, it works for me.
