### ISSUE TITLE
[BUG] border-opacity-* triggers "not a tailwind css class!" #108

### ISSUE THREAD

**Issue by harryduong91** [francoismassart/eslint-plugin-tailwindcss#111]
**Describe the bug**
border-opacity-10(0-100) triggers eslint no-custom-classname rules.

**To Reproduce**
1. Go to any `div`
2. Add className with `border-opacity-*`
3. See warning

**Expected behavior**
Should not show warning

**Screenshots**
![image](https://user-images.githubusercontent.com/95604794/151283150-35ceb53c-cf37-4bfa-b3fb-dacfdc7ca76f.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Softwares + version used:
     -  VSCode 1.63.2
     -  Tailwind 3.0.12
     - eslint-plugin-tailwindcss ^3.3.5

**Comment by francoismassart** [comment]
Hi @harryduong91 
This is not a bug, this is on purpose see this comment on similar issue with its possible actions 
https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/108#issuecomment-1021128802

**Comment by francoismassart** [comment]
Don’t hesitate if you need more infos or if you have questions 😉

**Comment by harryduong91** [comment]
Got it. Thanks @francoismassart

**Comment by francoismassart** [comment]
@harryduong91 in fact, I was wrong, there was something to fix in here.

`border-opacity-*` should not trigger `no-custom-classname` rule but trigger instead `migration-from-tailwind-2`.

I just fixed it in `eslint-plugin-tailwindcss@3.3.6`, it was released few minutes ago.

Thank you for bringing the issue.
