### ISSUE TITLE
[BUG] The `tailwindcss/enforces-negative-arbitrary-values` rule crashes when I use template literals in the `classNames` package

### ISSUE THREAD

**Issue by Serator** [francoismassart/eslint-plugin-tailwindcss#116]
**Describe the bug**
The `tailwindcss/enforces-negative-arbitrary-values` rule crashes when I use template literals in the `classNames` package.

**To Reproduce**
1. Type
```
import {memo} from 'react'
import cn from 'classnames'

export const Test = memo(function Test() {
  return <div className={cn(`test`)} />
})
```

2. See error: `ReferenceError: prefix is not defined`.

**Expected behavior**
There should be no error.

**Screenshots**
![image](https://user-images.githubusercontent.com/625005/151999448-83d7a9a2-b901-48b4-9fde-f35bc76dc040.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Softwares + version used:
     -  VSCode: 1.63.2
     - eslint-plugin-tailwindcss: 3.4.2
     - tailwindcss: 3.0.17

**Comment by francoismassart** [comment]
Good catch @Serator fixed in `v3.4.3`
