### ISSUE TITLE
[BUG] bg-opacity throws custom class errror

### ISSUE THREAD

**Issue by neldeles** [francoismassart/eslint-plugin-tailwindcss#123]
**Describe the bug**
`bg-opacity` classes throw custom class ESLint errors. 

If I correct it to the V3 syntax of `bg-opacity/75`, it throws this error:
<img width="636" alt="CleanShot-2022-02-17-at-12 03 21@2x" src="https://user-images.githubusercontent.com/14298160/154403254-888ce574-7908-4f59-a834-6a2df8807b5a.png">

If I use `bg-opacity-75` it throws this error:
<img width="638" alt="CleanShot-2022-02-17-at-12 02 59@2x" src="https://user-images.githubusercontent.com/14298160/154403262-4905348d-e855-40d0-9d27-ac45505dfb81.png">

**Expected behavior**
Shouldn't be detected as a custom class.

**Environment (please complete the following information):**
 TailwindCSS 3.0.13
 eslint-plugin-tailwindcss 3.4.4

**Comment by neldeles** [comment]
Closing because looks like it's related to this issue #88

**Comment by Ganbin** [comment]
I think this issue should be reopen.

I have the same issue. The problem is not the `migration-from-tailwind-2` but that the `*-opacity/X` throw the `Classname *-opacity/X is not a Tailwind CSS`.
