### ISSUE TITLE
[BUG] no custom classnames with tailwdincss/forms plugin

### ISSUE THREAD

**Issue by louislefebvre** [francoismassart/eslint-plugin-tailwindcss#125]
**Describe the bug**
With the plugin [tailwindcss/forms](https://github.com/tailwindlabs/tailwindcss-forms) installed through npm and setup in `tailwind.config.js` file, when using any of the classes of this plugin, eslint raise the following error:
- `Classname 'form-checkbox' is not a Tailwind CSS class! eslint tailwindcss/no-custom-classname`

This is an example with the class `form-checkbox`, but I could reproduce the issue with any other  class from the`form-*` classes.

**To Reproduce**
1. Install `tailwindcss/forms` through npm
2. Add it to the plugins in your `tailwind.config.js` file
3. Use any `form-*` className such as `form-input`, `form-checkbox`, ...
4. See error the eslint warning `tailwindcss/no-custom-classname`.

**Expected behavior**
I think it should not raise a warning for this? Or did I miss any configuration setup?

**Screenshots**
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/9850177/154998984-0c9ac932-17c3-401e-8f0c-9ee04c607cb3.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/9850177/154999039-0640d12e-d8f0-4b10-ad72-db1e1b962527.png">
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/9850177/154999147-34978399-ea8f-4e46-9b71-ff4dc2122e9e.png">

**Comment by francoismassart** [comment]
Hi @louislefebvre,
Are you sure the [`tailwindcss-forms`](https://github.com/tailwindlabs/tailwindcss-forms) is adding `form-...` classes ?
I did look in their doc but I don't see any extra classnames added by the plugin, only CSS selector like `[type='checkbox']`

**Comment by francoismassart** [comment]
👀  https://play.tailwindcss.com/GsuSflPCun?layout=horizontal

**Comment by louislefebvre** [comment]
Hello, thanks for the quick reply, you made me realise that I read too fast tailwindcss-forms documentation.
My bad, sorry for the inconvenience!
