### ISSUE TITLE
[BUG] Opacity suffix suggested when used properly

### ISSUE THREAD

**Issue by innocenzi** [francoismassart/eslint-plugin-tailwindcss#137]
**Describe the bug**
The `migration-from-tailwind-2` rules suggest using an opacity suffix instead of the `bg-opacity-*` classes. But in some cases, this is not possible nor wanted:

Here, we want to use `backdrop-blur`, except on Firefox because it does not support it. We also want a background opacity of 90% but we have no background class used.

**To Reproduce**
1. Use a `bg-opacity-*` class

**Expected behavior**
I would expect the rule not to be triggered when `bg-opacity-*` is used without a `bg-*` class or when used with a variant (`firefox:` here).

**Screenshots**
![image](https://user-images.githubusercontent.com/16060559/164200840-da8b059e-4733-41f8-9376-e455819fda59.png)

**Comment by Trkzi-Omar** [comment]
I had a similar issue, but figured it out by going back to the docs.
- It seems like you wanted to use `bg-opacity-*`  without a `bg-*` class. Which you can get around by using `bg-transparent/*` (e.g., `bg-transparent/75`). 
- As for usage with a variant, well it doesn't change anything (e.g., `hover:bg-transparent/25` ).

_PS: I just tried both of these examples locally and they behave as expected._

**Docs**: https://tailwindcss.com/docs/upgrade-guide#new-opacity-modifier-syntax

**Comment by innocenzi** [comment]
You're right. 👍
