### ISSUE TITLE
[BUG] `border-spacing-` class is not recognized

### ISSUE THREAD

**Issue by mongolyy** [francoismassart/eslint-plugin-tailwindcss#148]
**Describe the bug**
Border Spacing classes are not recognized.
https://tailwindcss.com/docs/border-spacing

**To Reproduce**
1. Go to table tag.
2. Use the border spacing e.g. `border-spacing-2`.
3. Run ESLint.
4. See error.

**Expected behavior**
I expected not to see this warning.

**Screenshots**
![2022-06-18_18h05_47](https://user-images.githubusercontent.com/10972787/174430920-439c566d-1e7f-4b1e-9880-a9eccb3371ad.png)

**Environment (please complete the following information):**
 - OS: windows 10
 - Package versions:
     - tailwindcss@3.1.3
     - postcss@8.4.14
     - eslint@8.18.0
     - eslint-plugin-tailwindcss@3.5.2

**Comment by francoismassart** [comment]
This is added in Tailwind CSS v3.1.0
https://github.com/tailwindlabs/tailwindcss/releases/tag/v3.1.0
I'll add it soon

**Comment by francoismassart** [comment]
WIP on #132

**Comment by mongolyy** [comment]
Thank you for your response!
I'll give it a try.

In a small way, I support your OSS activities!

**Comment by francoismassart** [comment]
I saw 😎thank you 🙏🏻

**Comment by francoismassart** [comment]
Any feedback on the latest beta @mongolyy ?

**Comment by mongolyy** [comment]
> Any feedback on the latest beta @mongolyy ?

Sorry for the delay in checking.
I just checked and it was working as expected.
Thanks!

**Comment by francoismassart** [comment]
Should be fixed in the [latest release `3.6.0`](https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v3.6.0)

Make sure to:

1. Update the `eslint-plugin-tailwindcss` package
2. Restart your editor
3. Report any issue on this repo
