### ISSUE TITLE
[BUG] Custom class in template string trips up parsing of class names

### ISSUE THREAD

**Issue by tupton** [francoismassart/eslint-plugin-tailwindcss#149]
**Describe the bug**
```
className={`p-0 custom-class-${index}`}
```
becomes
```
className={`custom-class- p-0${index}`}
```

**To Reproduce**
1. Enable the `classnames-order` rule and make sure `no-custom-classname` is disabled.
2. Combine a tailwind classname with a custom class in a template string with variable interpolation.
3. Run `eslint --fix`.
4. See the mangled class name .

**Expected behavior**
The fixed classname should include the entire custom class, including any interpolated variables, at the beginning of the classname string.

E.g. 

```
className={`custom-class-${index} p-0`}
```

**Environment (please complete the following information):**
 - OS: MacOS
 - Softwares + version used:
     -  eslint-plugin-tailwindcss v3.6.0
     -  node v14.19.3
     -  npm v6.14.17

**Comment by AndyOGo** [comment]
I have the same problem.

As a workaround I wrapped the dynamic class expression again, like:
```jsx
className={`p-0 ${`custom-class-${index}`}`}
```

**Comment by francoismassart** [comment]
Hi, this one is tricky to fix, for now I would encourage you to use the workaround...

**Comment by tupton** [comment]
The other obvious workaround is to split out the Tailwind and custom classes, e.g.

```ts
const twClasses = 'p-0'
const customClasses = `custom-class-${index}`

// …

<div className={`${twClasses} ${customClasses}`} … />
```
