### ISSUE TITLE
[Feature request] Support tailwind.config.ts

### ISSUE THREAD

**Issue by alvis** [francoismassart/eslint-plugin-tailwindcss#156]
**Is your feature request related to a problem? Please describe.**
Currently, `eslint-plugin-tailwindcss` automatically requires `tailwind.config.js` in CommonJS format and perform check against the config. However, if the config is in typescript or ESM format, it fails silently since `require` doesn't work with these files.

**Describe the solution you'd like**
No change needed. Just that `eslint-plugin-tailwindcss` would also recognise`tailwind.config.ts` alongside `tailwind.config.js`

**Comment by francoismassart** [comment]
Hi @alvis, can you provide a demo repo demonstrating what you are trying to accomplish ? Thanks

**Comment by francoismassart** [comment]
@alvis I guess this issue can be closed since the [previous `3.12.0` release](https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v3.12.0) supports ESM and TypeScript config files.

Can you confirm and close the issue if it is working for you ?

**Comment by alvis** [comment]
Hi @francoismassart! I double-checked with my code base, and I'm happy to confirm that it's working on 3.12. Thanks for following up :) +1
