### ISSUE TITLE
[QUESTION] eslint-plugin-tailwindcss + html + typescript

### ISSUE THREAD

**Issue by Shuunen** [francoismassart/eslint-plugin-tailwindcss#165]
Hello I'm wondering the best way to setup this plugin in a simple js/ts + html project

Here is how I managed to do it : 

https://github.com/Shuunen/issues/tree/eslint-plugin-tailwindcss-with-html-and-ts

Step 1 : Javascript only ✅ 

![image](https://user-images.githubusercontent.com/439158/189480657-2a773e99-3d5b-4f87-a13e-54410038be08.png)

Step 2 : Adding HTML support 🟢

![image](https://user-images.githubusercontent.com/439158/189481019-2adb7038-fdde-4518-86cb-d820c1c23530.png)

Step 3 : Adding TypeScript support 🟢

![image](https://user-images.githubusercontent.com/439158/189481172-05520510-60c4-43c8-aef4-4efafd18c911.png)

Step 4 : Adding an eslint rule 🔴

![image](https://user-images.githubusercontent.com/439158/189481376-b3a6112f-556d-4e7e-9d36-6691f8aefdbc.png)

Step 5 : Moving rule & parse to another override 🟢

![image](https://user-images.githubusercontent.com/439158/189481569-c937d689-f25f-4d9c-a2f0-ec82d8868361.png)

**Environment**
 - OS: Windows 10 x64
 - Softwares + version used:
     -  VSCode 1.71
     -  Node 16

What do you think ? 

Is there any way to simplify this ?

Regards

**Comment by francoismassart** [comment]
Hi @Shuunen, 
thank you for your exhaustive message, I'll take a look to see if it would be possible to add this to the recommended settings.

**Comment by francoismassart** [comment]
It works. I’ll update the recommended settings soon. Thanks 🙏🏻

**Comment by francoismassart** [comment]
I added few default parsers based on file extensions inside the [`recommended` preset](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/lib/index.js#L24) of `v3.8.1`

It should reduce the required configuration 😉

**Comment by Shuunen** [comment]
Great I'll let you know how it's going with this new release

Thanks François 👍

**Comment by francoismassart** [comment]
@Shuunen, it looks like this change is not wise because it creates more issues than it solves, see my comment 
👉 https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/203#issuecomment-1401562737

I'm gonna revert it but update the documentation 😅

**Comment by Shuunen** [comment]
@francoismassart I'm not sure about that, let's talk about this in the other issue
