### ISSUE TITLE
[BUG] trying to add an arbitrary background position and background image seem to conflict.

### ISSUE THREAD

**Issue by isaackearl** [francoismassart/eslint-plugin-tailwindcss#172]
**Describe the bug**
I get an error of type 'no-contradicting-classname' for 2 things that do not contradict.

**To Reproduce**
create a div that has these 2 tailwind classes:
hover:bg-[url(@projectFolder/bulletSquareGreen.png)] hover:bg-[3%_center]

**Expected behavior**
nothing, these are two valid arbitrary classes.  ones puts a background-image and one does background-position

**Comment by terraelise** [comment]
This is also happening for me, but the second class is standard:
`Error: Classnames bg-[url('/images/banner.png')], bg-top are conflicting!`

**Comment by chrishuman0923** [comment]
Same here.

Error: `Classnames bg-[url(@images/home/hero.jpeg)], bg-[top_right] are conflicting!`

If there is a way to write this as one class to make the plugin happy and the error go away, would love to know.

**Comment by francoismassart** [comment]
@isaackearl, @terraelise & @chrishuman0923 please try updating to the latest version and let me know if we can close this issue.

`npm i eslint-plugin-tailwindcss@3.12.1` or simply `npm i eslint-plugin-tailwindcss`

Thank you for your feedback

**Comment by pm0u** [comment]
@francoismassart had this issue on 3.12.0-beta.0 and updated to 3.12.1 and can confirm it resolved.
