### ISSUE TITLE
[Question] Vue/Nuxt Support

### ISSUE THREAD

**Issue by tillmon** [francoismassart/eslint-plugin-tailwindcss#18]
I tried to make this plugin work with Nuxt, but failed so far. Is that something what can be configured or is it not supported?

**Comment by francoismassart** [comment]
Hi @tillmon,
The plugin is currently not tested in Vue but it could be adapted to do so when I have some time on my hand.

**Comment by iraklisg** [comment]
It would be great to be able to use this plugin with Vue SFC

**Comment by francoismassart** [comment]
I’ll take a look at the PR asap.

**Comment by francoismassart** [comment]
More info: https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v1.11.0 

Thank you for contributing @DanSnow 👍
