### ISSUE TITLE
[BUG] The auto-fix for enforces-shorthand incorrectly rewrites p-2 pl-2 pr-2 to just px-2

### ISSUE THREAD

**Issue by cmlenz** [francoismassart/eslint-plugin-tailwindcss#182]
**Describe the bug**
The auto-fix for `enforces-shorthand` rewrites `p-2 pl-2 pr-2` to just `px-2`, although `p-2` would be correct.

**To Reproduce**
1. Open a file that is covered by ESLint
2. Edit a className to say `p-2 pl-2 pr-2`
3. Apply auto-fix
4. The className will now be `px-2`

**Expected behavior**
The resulting class name should be `p-2`

**Screenshots**

**Environment (please complete the following information):**
`eslint-plugin-tailwindcss` version 3.7.0

**Comment by francoismassart** [comment]
Hi @cmlenz,
thank you for reporting the issue.

This was an easy fix.

Available via the latest release

`npm i eslint-plugin-tailwindcss@3.7.1`

https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v3.7.1

**Comment by cmlenz** [comment]
That was quick, thanks for the fix!
