### ISSUE TITLE
[Feature request] Support for named group syntax in no-custom-classname

### ISSUE THREAD

**Issue by cmlenz** [francoismassart/eslint-plugin-tailwindcss#183]
**Is your feature request related to a problem? Please describe.**
Tailwind CSS 3.2 introduced a new syntax for naming groups, see https://tailwindcss.com/blog/tailwindcss-v3-2#nested-group-and-multiple-peer-support-using-variant-modifiers

This syntax is incorrectly reported as a custom class by `tailwindcss/no-custom-classname` rule.

**Describe the solution you'd like**
The rule should be updated to recognize named groups.

**Comment by redocecin** [comment]
Looking forward to this feature!

**Comment by atoulmet** [comment]
Hi! Thanks for creating the issue @cmlenz 🙏 Have you found a clean way to make the warning disappear?

**Comment by cmlenz** [comment]
> Have you found a clean way to make the warning disappear (instead of disabling `tailwindcss/no-custom-classname`)?

@atoulmet No, that's what we've done for now.
