### ISSUE TITLE
[BUG] Bad Performance

### ISSUE THREAD

**Issue by coolswood** [francoismassart/eslint-plugin-tailwindcss#194]
**Describe the bug**
On my work project it slows down the build very much. From about 0.45s to 4min.

**To Reproduce**
Set plugin:tailwindcss/recommended to .eslintrc

**Environment (please complete the following information):**
 - OS: macOS
 - Softwares + version used:
     -  node v16.13.0

**Additional context**

**eslint config file or live demo**
```
{
  "extends": [
    "plugin:@typescript-eslint/recommended",
    "plugin:react/recommended",
    "plugin:import/typescript",
    "plugin:@next/next/recommended",
    "plugin:tailwindcss/recommended"
  ],
  "plugins": [
    "@typescript-eslint",
    "react-hooks",
    "immutable",
    "import",
    "@next/eslint-plugin-next",
    "disable-autofix",
    "tailwindcss"
  ],
  "env": {
    "browser": true,
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 2018,
    "sourceType": "module",
    "project": "./tsconfig.json",
    "ecmaFeatures": { "jsx": true }
  },
  "rules": {
    ...
  },
  "settings": {
    "react": { "version": "detect" },
    "tailwindcss": { "callees": ["mergeClassnames"] }
  }
}
```

**Comment by francoismassart** [comment]
Hi
Difficult to tell what’s wrong without a demo project but I’m guessing it could be related to the parsing of CSS files. 
Do you use a lot of CSS files ? Try providing a short/restricted list of CSS files via the globs option 
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/no-custom-classname.md#cssfiles-default-css-node_modules--dist-build

**Comment by coolswood** [comment]
@francoismassart We don't use css files, but styled-components. We migrate to tailwind. Could this be causing a problem?

**Comment by francoismassart** [comment]
A demo project demonstrating the issue could really help. Without it, I can’t really help as most users do not get these huge build times. 

Maybe try proving an empty array for the cssFiles option…

**Comment by coolswood** [comment]
Ok, I will try to provide smt

**Comment by francoismassart** [comment]
Closing the issue, please re-open it if you can provide a minimalist project demonstrating the issue. 

Performances seems acceptable for most of the other users of the plug-in.
