### ISSUE TITLE
[BUG] No support for html extension file linting?

### ISSUE THREAD

**Issue by LimEunSeop** [francoismassart/eslint-plugin-tailwindcss#198]
Is it only works for JS file which is used by... such as React or Vue?

**Comment by francoismassart** [comment]
Hi @LimEunSeop,

Yes you can lint HTML, but you must use another parser.

I've made a demo of linting HTML files on this repo:
https://github.com/francoismassart/demo-eslint-plugin-tailwindcss/tree/html-files#demo-eslint-plugin-tailwindcss

Let me know if it works for you 😉

**Comment by LimEunSeop** [comment]
@francoismassart

Thank you! It works well.

My .eslintrc.json file contains

```json
{
  "plugins": ["tailwindcss"],
  "overrides": [
    {
      "files": ["*.html"],
      "parser": "@angular-eslint/template-parser",
      "extends": ["plugin:tailwindcss/recommended"]
    }
  ]
}

```
