### ISSUE TITLE
Template Literal Sorting? [Feature request]

### ISSUE THREAD

**Issue by soundsystems** [francoismassart/eslint-plugin-tailwindcss#199]
**Is your feature request related to a problem? Please describe.**

It's annoying that className template literals which include tailwind utility classes are not sorted.

**Describe the solution you'd like**

Be able to sort template literal statements properly with eslint-plugin-tailwindcss

**Describe alternatives you've considered**

**Additional context**

Would this be possible?

**Comment by francoismassart** [comment]
Hi,
Can you provide a short code example ?
Thank you

**Comment by francoismassart** [comment]
@soundsystems please reopen this ticket when you can provide a code snippet demonstrating the issue.
Template literals are linted but _not as whole_, **only its inner parts** .
