### ISSUE TITLE
[BUG] Handle `undefined` as `className`

### ISSUE THREAD

**Issue by thebuilder** [francoismassart/eslint-plugin-tailwindcss#20]
If using `clsx` (or similar) it's possible the `className` will be set to `undefined` (or another, non string value). 
This however throws an error when the plugin tries to parse the value. 

```
TypeError: Cannot read property 'length' of undefined
Occurred while linting /docs/styleguide/blocks/colors.tsx:17
    at Object.getClassNamesFromAttribute (/node_modules/eslint-plugin-tailwindcss/lib/util/attr.js:35:35)
    at Object.parseNodeRecursive (/node_modules/eslint-plugin-tailwindcss/lib/util/ast.js:94:27)
    at /node_modules/eslint-plugin-tailwindcss/lib/rules/no-contradicting-classname.js:135:19
```

Code that triggers the error:

```jsx
<div
  className={clsx(
    "w-full h-10 rounded",
    name === "white"
      ? "ring-black ring-1 ring-opacity-25 ring-inset"
      : undefined
  )}
/>
```

Guessing it should validate if the value is valid before attempting to parse it.

This occurs after upgrading to `1.8.0`. The same code works fine with `1.7.0`.

**Comment by francoismassart** [comment]
@thebuilder could you try to reproduce the issue using the latest release ? `v1.8.2` ? Let me know if this works for you

**Comment by thebuilder** [comment]
Perfect - The above snippet works great now. It also managed to sort the classes correctly with `--fix`.
