### ISSUE TITLE
[Feature request] Better Readme Instructions

### ISSUE THREAD

**Issue by kerns** [francoismassart/eslint-plugin-tailwindcss#200]
**Is your feature request related to a problem? Please describe.**
The installation instructions are not as clear as they could be. Some ambiguity in the language about what should be edited where, and missing visuals that provide a complete overview. 

**Describe the solution you'd like**
I would like to be contacted if you are interested in improving them. Happy to make a PR but I have to get some answers first. 😅

**Additional context**
A lot of people coming to Tailwind are not hardcore devs, have more...designer brains, or just think differently, and need instructions to assume less about your level of experience. The good news is that writing to this audience will be better for all audiences.

**Comment by francoismassart** [comment]
Hi @kerns ,
I just published `v3.8.1` which 

- reduces the minimum required configuration steps by including default parsers per file extension in the `recommended` preset (see https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/165)
- rewrite the [install instructions on the README](https://github.com/francoismassart/eslint-plugin-tailwindcss#installation)
- I'm also working on a screencast "Getting started" for eslint-plugin-tailwindcss.

Please take a look and let me know if you see additional enhancements that can be done
