### ISSUE TITLE
Angular/Vue dependencies installed in React project

### ISSUE THREAD

**Issue by LauSam09** [francoismassart/eslint-plugin-tailwindcss#207]
**Describe the bug**
Dependencies for Angular/Vue projects are installed even though my project is React-based. I would have expected these to be peer dependencies so that unnecessary dependencies are excluded, e.g. see the [alloy lint config](https://github.com/AlloyTeam/eslint-config-alloy/blob/master/package.json#L118).

**To Reproduce**
1. Install `eslint-plugin-tailwindcss` as a development dependency in a React project.
2. Observe that dependencies for Angular and Vue are installed.

**Expected behavior**
Angular/React/Vue dependencies are peer dependencies.

**Screenshots**
n/a

**Environment (please complete the following information):**
 - OS: Windows 10
 - Softwares + version used:
     -  VSCode 1.74.3
     -  yarn 3.3.0, node 16.18.0

**Additional context**
n/a

**eslint config file or live demo**
n/a

**Comment by francoismassart** [comment]
@LauSam09 
I’m planning to move the default parsers out of the recommended settings into a dedicated package 😉

**Comment by LauSam09** [comment]
That's interesting, what would that look like in terms of dependencies then - would a TypeScript project install `eslint-plugin-tailwindcss` as well as this new dedicated package?

Also, I'm seeing peer dependency warnings after installing this package. I have the dependencies installed myself so I believe it's because `eslint-plugin-tailwindcss` doesn't name them as dependencies? Perhaps your package change will resolve this as well?

![image](https://user-images.githubusercontent.com/24778857/215718237-9719d293-1f8a-4892-9624-3ab5bcc28857.png)

**Comment by francoismassart** [comment]
Fixed in the latest release `v3.8.3`

**Comment by LauSam09** [comment]
Confirmed that the latest release has resolved this for us. Thanks.
