### ISSUE TITLE
[BUG] Fixer makes template un-usable in Angular inline Templates

### ISSUE THREAD

**Issue by dolanmiu** [francoismassart/eslint-plugin-tailwindcss#213]
**Describe the bug**
The fixer alters the template, removes the quotation mark on the left hand side, and adds an extra character on the right hand side:

From this:

```ts
@Component({
  selector: 'app-device',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `<div class="min-h-screen flex"><router-outlet></router-outlet></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DeviceComponent {}
```

To This:

```ts
@Component({
  selector: 'app-device',
  standalone: true,
  imports: [CommonModule, RouterModule],
  template: `<div class=flex min-h-screenx"><router-outlet></router-outlet></div>`,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DeviceComponent {}
```

**To Reproduce**
1. Create an Angular application
2. Use inline templates
3. Run the auto-fixer in VSCode

**Expected behavior**
Fixer should work as expected

**Environment (please complete the following information):**
 - OS: Windows 10
 - VSCode

**Additional context**

**eslint config file or live demo**

![Animation](https://user-images.githubusercontent.com/2917613/219900974-31d70201-5c19-492b-9bd7-c9d8812bd95d.gif)

**Comment by francoismassart** [comment]
@dolanmiu I tried reproducing this but on my test project the value of `template` inside `@Component` does not get parsed by eslint-plugin-tailwindcss.

Would you mind create and share a repo demonstrating the issue ?

Thanks

**Comment by dolanmiu** [comment]
@francoismassart sorry about the late response, here is the repo with the bug reproduced

https://github.com/dolanmiu/eslint-plugin-tailwind-classname-order-bug

Run the usual commands to get started:

```
$ npm install
$ npm run lint
```

Then try the fixer on VS Code.

![image](https://user-images.githubusercontent.com/2917613/221378461-da4a239c-7a16-4ab6-aadf-19f89f28bf69.png)

**Comment by francoismassart** [comment]
The range extracted from the node:
start: `node.valueSpan.fullStart.offset`
end: `node.valueSpan.end.offset`

is incorrect but is works on existing test also using `@angular-eslint/template-parser` see https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/tests/lib/rules/migration-from-tailwind-2.js#L239

Patching the offset would make the existing test fail.

So, I must find out why the generated range is incorrect... WIP

**Comment by francoismassart** [comment]
Not sure but may be related to this ? https://github.com/jerone/eslint-plugin-angular-template-consistent-this/commit/fb7c29c73c3f952fece51a43ef34bcf577ab3184#diff-da10bcc7d8dff796f50c9358a7268eb5abd2c50f460aecc4b2be1c691a966224R88-R118

**Comment by dolanmiu** [comment]
Where you able to clone my repo and reproduce it on your side though?

What about compensating for the offset? lol

**Comment by francoismassart** [comment]
@dolanmiu I need to find out what is causing the offset but what I could try as a workaround is to add an `rangeOffset`setting which would allow you to manually fix the issue via a change in the configuration until we find out the cause of this.

**Comment by francoismassart** [comment]
> Notice, on the GIF I posted, the squiggly yellow underline is in the wrong place too. Is it all related?

I can see it on your GIF but on my demo repo I got it underlined at the correct range:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/704026/221827783-bd65359b-0d77-47b1-82e4-b2826403c7ad.png">

**Comment by francoismassart** [comment]
@dolanmiu there is something funky in your demo repo around the eslint config.

When I try to override some settings for specific files like so (simplified):

```json5
{
  "root": true,
  "ignorePatterns": ["projects/**/*"],
  "extends": [
    "plugin:tailwindcss/recommended"
  ],
  "overrides": [
    {
      "files": ["*.ts"],
      "rules": {
        "tailwindcss/classnames-order": [
          "warn",
          {
            "rangeOffset": 1
          }
        ]
      }
    },
    {
      "files": ["*.html"],
      "rules": {
        "quotes": ["warn", "double"],
        "tailwindcss/classnames-order": [
          "error",
          {
            "rangeOffset": 0
          }
        ]
      }
    }
  ]
}
```

The last value of `rangeOffset` also apply on `*.ts` files...

**Comment by francoismassart** [comment]
Normal behaviour would be like so

eslintrc
![image](https://user-images.githubusercontent.com/704026/222075535-ef45050f-a477-4998-8ac3-7ce50237ece5.png)

results
![image](https://user-images.githubusercontent.com/704026/222075647-e5c5327d-c8f5-4a4b-885b-4065f2735899.png)

**Comment by francoismassart** [comment]
I believe this is a side effect of using process-inline-templates

**Comment by francoismassart** [comment]
- I have no way of determining if the parsed code is within an inline template
- The workaround using an extra setting `rangeOffset` cannot be used as only the last declared options are remaining (see also next point)
- I believe this issue is not on our side but may be an incorrect location sent by the parser due to using [process-inline-templates](https://github.com/angular-eslint/angular-eslint/blob/main/packages/eslint-plugin-template/src/configs/process-inline-templates.json)

Can't do it 🤭

**Comment by dolanmiu** [comment]
> @dolanmiu there is something funky in your demo repo around the eslint config.
> 
> When I try to override some settings for specific files like so (simplified):
> 
> ```js
> {
>   "root": true,
>   "ignorePatterns": ["projects/**/*"],
>   "extends": [
>     "plugin:tailwindcss/recommended"
>   ],
>   "overrides": [
>     {
>       "files": ["*.ts"],
>       "rules": {
>         "tailwindcss/classnames-order": [
>           "warn",
>           {
>             "rangeOffset": 1
>           }
>         ]
>       }
>     },
>     {
>       "files": ["*.html"],
>       "rules": {
>         "quotes": ["warn", "double"],
>         "tailwindcss/classnames-order": [
>           "error",
>           {
>             "rangeOffset": 0
>           }
>         ]
>       }
>     }
>   ]
> }
> ```
> 
> The last value of `rangeOffset` also apply on `*.ts` files... Also problems are all reported as "error" instead of "warnings" for `*.ts` files...

This funky eslint config is unfortunately the opinionated pre-generated Angular eslint.

I will raise a ticket on their end

**Comment by dolanmiu** [comment]
Ok, I have created an issue over there:

https://github.com/angular-eslint/angular-eslint/issues/1319

Let's hope for the best
