### ISSUE TITLE
[BUG] classRegex ignored in vuejs

### ISSUE THREAD

**Issue by mathieutu** [francoismassart/eslint-plugin-tailwindcss#216]
Hi,
Thanks for the great work!

**Describe the bug**
When in vueJS [templates case](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/893c44d288c07ed56d0dcaf7e5db10893854c03a/lib/util/ast.js#L41), the [checks are made](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/893c44d288c07ed56d0dcaf7e5db10893854c03a/lib/util/ast.js#L43) against `class` token, and not against the defined `classRegex`.

**To Reproduce**
1. Add classRegex to settings
2. Add classes to an attribute that is concerned by the regex.

**Expected behavior**
Any vue attributes concerned by classRegex should be validated.

**Environment (please complete the following information):**
 - OS: macOS
 - Eslint last version

Thanks!

**Comment by francoismassart** [comment]
Hi @mathieutu,
please try this beta version:

`npm i eslint-plugin-tailwindcss@3.10.1-beta.3 -D`

and let me know if it works for you

**Comment by francoismassart** [comment]
@mathieutu can you provide a real world example of `classRegex` + `vuejs` in the comments so that I can easily add unit tests as well ?

**Comment by mathieutu** [comment]
It's working great, thanks!

There is a native component in VueJS called Transition which has the following props: 
- `enterActiveClass`
- `enterFromClass`
- `enterToClass`
- `leaveActiveClass`
- `leaveFromClass`
- `leaveToClass`

So my classRegexp is simply `class$`. (as the keyname will be lowercase at the time of the check)

**Comment by mathieutu** [comment]
Yeah, but as I'm using twUI, it's better if I can avoid adding a function to all the properties 😅 

(Also, it's not best to add a runtime function just for linting.)

**Comment by francoismassart** [comment]
👉 `eslint-plugin-tailwindcss@3.10.1`
