### ISSUE TITLE
[Feature request] eslint settings config support multiple tailwind config

### ISSUE THREAD

**Issue by Muromi-Rikka** [francoismassart/eslint-plugin-tailwindcss#219]
eslint settings config support multiple tailwind config

```json
{
  "settings": {
    "tailwindcss": {
      "config": ["apps/project1/tailwind.config.js"]
    }
  }
}

```

**Comment by francoismassart** [comment]
@Muromi-Rikka can you provide more infos: docs or links, use cases etc. ?

**Comment by Muromi-Rikka** [comment]
@francoismassart My project is a monorepo project, which has multiple tailwind.config.js, but the configuration file can only specify a single configuration

**Comment by francoismassart** [comment]
I guess you could define several parts inside your eslintrc file or even use different eslintrc files pointing each to its related files and tailwind config... I can give it a shot if you take the time to provide a simple demo project with 2apps and 2 configs.

**Comment by francoismassart** [comment]
@Muromi-Rikka 
here is an example, there might be other way to do it too.

## app-one

```js
// .eslintrc.js of app-one
const path = require('path');
module.exports = {
  settings: {
    tailwindcss: {
      config: path.join(__dirname, "tailwind.config-one.js"),
    }
  }
};
```

```js
// tailwind.config-one.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{php,html,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        one: '#B4D455'
      }
    },
  },
  plugins: [],
}
```

## app-two

```js
// .eslintrc.js of app-two
const path = require('path');
module.exports = {
  settings: {
    tailwindcss: {
      config: path.join(__dirname, "tailwind.config-two.js"),
    }
  }
};
```

```js
// tailwind.config-two.js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{php,html,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        two: '#B4D455'
      }
    },
  },
  plugins: [],
}
```

Clone this branch https://github.com/francoismassart/demo-eslint-plugin-tailwindcss/tree/multiple-apps

`npm i` and try running `npm run lint`

=>

<img width="792" alt="image" src="https://user-images.githubusercontent.com/704026/222399850-90d2009d-3531-4098-8bb8-4f12a85b1baf.png">

Notice app-one accepts `text-one` and raise a warning for `text-two` as `custo-classname`
Notice app-two accepts `text-two` and raise a warning for `text-one` as `custo-classname`

I have 3 eslintrc files:
- shared rc
- app-one rc
- app-two rc

Take a look at them

**Comment by francoismassart** [comment]
If this helped you out, please share the project on social medias 😉

**Comment by Muromi-Rikka** [comment]
Thanks, but I currently only have one eslintrc configuration, I think I may need to modify the lint detection

**Comment by francoismassart** [comment]
Just add the additional eslintrc files is your different apps folder, eslint will "look up" for extra eslintrc files next to the current parsed file and up...

The deeper the eslintrc file is, the stronger its settings are reflected.

At the end, eslint merges all the rc files it found together
