### ISSUE TITLE
[BUG] Support eslint's new config file (flat) for recommended rules

### ISSUE THREAD

**Issue by beorn** [francoismassart/eslint-plugin-tailwindcss#280]
When using [eslint's new config file format](https://eslint.org/docs/latest/use/configure/configuration-files-new), such as this `eslint.config.js`:
```ts
import tw from "eslint-plugin-tailwindcss"

export default [
  tw.configs.recommended
]
```

Errors out:

> Oops! Something went wrong! :(
> ESLint: 8.50.0
> A config object has a "plugins" key defined as an array of strings.
> Flat config requires "plugins" to be an object in this form:
>    {  plugins: {  tailwindcss: pluginObject  } }
> Please see the following page for information on how to convert your config object into the correct format:
https://eslint.org/docs/latest/use/configure/migration-guide#importing-plugins-and-custom-parsers
> If you're using a shareable config that you cannot rewrite in flat config format, then use the compatibility utility:
https://eslint.org/docs/latest/use/configure/migration-guide#using-eslintrc-configs-in-flat-config

Is there a way to add recommended tailwind rules using ESlint's new config format?

**Comment by francoismassart** [comment]
Hi @beorn 
The plugin doesn't support the new config format yet.
Do you use other 3rd party eslint linter which support it so that I can see how to implement it ?

**Comment by awdr74100** [comment]
Hi @francoismassart
The [@antfu/eslint-config](https://github.com/antfu/eslint-config) widely used in vue or nuxt is flat style, maybe you can refer to how he does the convert?
It would be great to be able to combine them!

**Comment by Sun-ZhenXing** [comment]
@awdr74100, this is my temporary method.

https://github.com/Sun-ZhenXing/algo-code-mgr/blob/main/eslint.config.js

**Comment by beorn** [comment]
@Sun-ZhenXing Yes, thanks, it seems like using `FlatCompat.compat` is the best way currently.  Ideally there should be some mention of this in the docs and/or useful error/warning messages when you do it wrong.

**Comment by thenbe** [comment]
A migration guide has been added to eslint's docs: https://eslint.org/docs/latest/extend/plugin-migration-flat-config

**Comment by itpropro** [comment]
We only use project that use eslint flat config at this point, any updates to this being supported?

**Comment by kachkaev** [comment]
@itpropro you can use this workaround: https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/280#issuecomment-1746781848. There is no need to wait till all plugins have migrated to flat config.

**Comment by irg1008** [comment]
Be careful you need to use `...compat.config({...})` and not `...compat.extends({...})`

**Comment by tylerolson** [comment]
Tailwindcss errors/warnings appear when I manually run `eslint .` but do not appear in vscode no matter what I try. General eslint and vue errors appear. This means that tailwind auto sorting is only working when I manually run `eslint . --fix`

My `package.json` has these scripts:

```
"lint": "eslint .",
"lint:debug": "eslint . --debug",
"lint:fix": "eslint . --fix"
```
Seems to be a vscode errors, Ive tried literally everything.

**Comment by DavidDeSloovere** [comment]
I have this, and many other changes, in `.vscode/settings.json` - maybe that's the missing piece
```jsonc
{
  /****************************************
   * Ant Fu eslint
   ****************************************/
  // https://github.com/antfu/eslint-config#vs-code-support-auto-fix
  // Enable the ESlint flat config support
  "eslint.experimental.useFlatConfig": true,
  ..........
}
```

**Comment by romansp** [comment]
@tylerolson it definitely works in VS Code via compat as already confirmed by several others in this thread. 

It's hard to help you without seeing the full code of your configuration. Please submit a minimal repro.

**Comment by vinavinas** [comment]
> Still can't get eslint-plugin-tailwindcss to show up in vscode. Not sure if I should keep trying, make a new issue, or be stuck with prettier.

I was using eslint@^9.0.0 with `FlatCompat` when I encountered the same issue. I reverted to eslint@^8.0.0 and it worked fine.

**Comment by grokpot** [comment]
Just some stranger on the internet here to say thanks to all of you above - this is such a niche issue 
("I want to sort my TailwindCSS classes with Antfu, but Antfu and Tailwind had a public falling out so there's not official support and now I'm down into a github issue")

And it works!
This is what makes the internet great. Thanks everyone!
