### ISSUE TITLE
[BUG] `touch-action` classes should be considered combinable

### ISSUE THREAD

**Issue by timmywil** [francoismassart/eslint-plugin-tailwindcss#293]
**Describe the bug**

`touch-action` classes have been combinable [for a couple years now](https://github.com/tailwindlabs/tailwindcss/pull/6115), but this plugin considers them exclusive.

**To Reproduce**
1. Use both `touch-pan-x` and `touch-pan-y` on the same element.

**Expected behavior**
No error.

**Environment (please complete the following information):**
 - OS: windows 11
 - Software + version used:
     -  eslint-plugin-tailwindcss 3.13.0
     -  tailwindcss 3.3.6

**Additional context**

**eslint config file or live demo**
By providing a link to a live demo, a demo video or a github repo fixing the issue will be easier.
https://stackblitz.com/edit/eslint-plugin-tailwindcss-edit?file=package.json

**Comment by francoismassart** [comment]
👋 @timmywil 
I made a Tailwind Play to demonstrate the different cases and it should be easily fixed in the next release.

https://play.tailwindcss.com/vJfYBye86o

**Comment by francoismassart** [comment]
Please try this beta version:

`npm i eslint-plugin-tailwindcss@3.14.2-beta.1 -D`

and give me feedbacks.

**Comment by timmywil** [comment]
Looks good to me, thanks!

**Comment by francoismassart** [comment]
Fixed in the latest release `eslint-plugin-tailwindcss@3.14.2`
