### ISSUE TITLE
[BUG] className shadow-md and shadow-[#custom-color] are conflicting

### ISSUE THREAD

**Issue by rlawlsyoung** [francoismassart/eslint-plugin-tailwindcss#298]
**Describe the bug**
`shadow-md, shadow-[#customcolor]` are conflicting.
But, `shadow-md shadow-cyan-500` are not conflicting.
I'm not familiar with tailwind so I'm not sure, but I suspect it's a bug

**To Reproduce**
1. Add the className `shadow-md shadow-[#customcolor]` to a single HTML tag. (shadow size can be any size)
2. Run `eslint ./src --fix` command
3.  Error: Classnames shadow-md, shadow-[#customcolor] are conflicting!
4. But, `shadow-md shadow-cyan-500` are not conflicting.

**Screenshots**
![스크린샷 2023-12-21 오후 6 17 54](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/100749629/7f97bc03-1f28-46ad-8c01-61beb0034526)

**Environment (please complete the following information):**
 - OS: Mac OS
 - Softwares + version used: Node v18.17.0 + pnpm 8.9.0

**Comment by francoismassart** [comment]
@rlawlsyoung Please try this beta version:

`npm i eslint-plugin-tailwindcss@3.14.2-beta.1 -D`

and give me feedbacks.

**Comment by francoismassart** [comment]
Fixed in the latest release `eslint-plugin-tailwindcss@3.14.2`
