### ISSUE TITLE
[BUG] tailwindcss/enforces-shorthand reports false positive

### ISSUE THREAD

**Issue by iscekic** [francoismassart/eslint-plugin-tailwindcss#307]
**Describe the bug**
For some combinations of `h-` and `w-` classes, a `size-` equivalent does not exist, yet the rule reports them as invalid.

**To Reproduce**
1. Try setting class values to `h-screen w-screen`

**Expected behavior**
No error reported as `size-screen` doesn't exist per [the docs](https://tailwindcss.com/docs/size)

**Screenshots**
N/A

**Environment (please complete the following information):**
 - `"eslint-plugin-tailwindcss": "3.14.0"`

**Additional context**
The rule also reports false positives for custom values which don't exist in the tailwind config. Eg, I have `30` and `60` defined for width and height, but not for size - therefore `h-30 w-30` can't be replaced by `size-30`.

**Comment by ryan-dahlia** [comment]
+1 We are also showing unexpected `size-screen` warnings 

However, we are also seeing new warnings that seem valid, that were not present in the previous release.

`Warning: Classnames 'h-8, w-8' could be replaced by the 'size-8' shorthand!`

Thank you @francoismassart for this plugin!

**Comment by elussich-globant** [comment]
+1 We are seeing unexpected `size-screen` warnings in `v3.14.0`. Doing a quick search for `size-screen` in the TailwindCSS repo, it doesn't seem that particular shorthand exists.

Thanks for the plugin!

**Comment by francoismassart** [comment]
Indeed, the following `size-*` classnames are invalid:

- `size-screen`
- `size-svw`
- `size-lvw`
- `size-dvw`

**Comment by bbuilds** [comment]
@francoismassart  this seems to fix the same issue I was having as 

> @iscekic @Raithdk @elussich-globant @ryan-dahlia @patrikholcak Please use the latest beta until it is published: `npm i eslint-plugin-tailwindcss@3.14.1-beta.1 -D`
> 
> and as always please provide feedback in this issue 👍

this seems to fix the same issue I was having as [Raithdk](https://github.com/Raithdk)

**Comment by wbiller** [comment]
The issue that `h-screen w-screen` gets replaced by `size-screen` still exists in 3.14.2.
