### ISSUE TITLE
[Feature request] HTML support in Flat config

### ISSUE THREAD

**Issue by LatenPath** [francoismassart/eslint-plugin-tailwindcss#309]
**Is your feature request related to a problem? Please describe.**
Currently, the plugin not supported flat config. 

**Describe the solution you'd like**
I want to use it not only for `js/ts` file, but also for `html` file with `flat config`.

**Additional context**
This is my `flat config` look like:
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/ec888d3c-4b5f-4b40-b773-c824f9c2b5f6)

And `Compat` solution made plugin work with `js` file:
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/b8e81448-51af-41f7-979c-a20017657af9)

But I want it also work in `HTML` file:
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/0b92aba7-02b0-41cc-86ec-029d76f10551)

I try import the `parser` like in document:
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/f1bedc1f-10df-4e8b-a424-c35a9aa466e4)
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/7bc0e28c-46ed-4bfa-a482-f7e6fbd859d4)

But it throw the error:
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/145383056/ab6c0b9b-1c58-4804-9308-a5dca102849f)

Please help me 😢

**Comment by mcfarljw** [comment]
You can find a workaround here https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/280.

**Comment by LatenPath** [comment]
I can't solve my issue with Compat solution. I will wait for Flat config support in future.
