### ISSUE TITLE
[BUG] tailwindcss/enforces-shorthand try to shorthand 'inset-y-0' with a whitespace

### ISSUE THREAD

**Issue by Senbonzakura1234** [francoismassart/eslint-plugin-tailwindcss#312]
**Describe the bug**
The rule try to shorthand 'inset-y-0' with a whitespace before an appending template string variable

**To Reproduce**

try typing this JSX:
``<div className={`absolute inset-y-0 left-0 w-1/3 rounded-[inherit] shadow-lg ${className}`} />``
got lint warning `Classnames '' could be replaced by the 'inset-y-0' shorthand! eslint (tailwindcss/enforces-shorthand)`
format the code and it change to:
``<div className={`absolute inset-y-0 left-0 w-1/3 rounded-[inherit] shadow-lg${className}`} />``

**Expected behavior**
Expect it not to remove the whitespace, no lint warning
``<div className={`absolute inset-y-0 left-0 w-1/3 rounded-[inherit] shadow-lg ${className}`} />``

**Screenshots**
![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/43206347/32d54d7d-526e-4cd7-a7f4-b28a1bf49194)

**Environment (please complete the following information):**
 - OS: windows 11
 - Softwares + version used:
     -  VSCode 1.85.2
     - pnpm@8.14.1 node@18.18.2 Terminal@1.18.3181.0

**eslint config file or live demo**
https://github.com/Senbonzakura1234/sophie-dex

**Comment by francoismassart** [comment]
👋  @Senbonzakura1234 
can you try the latest beta by running

`npm i eslint-plugin-tailwindcss@3.14.1-beta.0 -D` ?

And then try to reproduce the issue ? I added a test case which runs fine.

Thank you for your feedback

**Comment by rodrigo-araujo-9731** [comment]
This is also happening to me when using "h-20 w-20" (for example). 

![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/65397328/f7efac22-3a54-49a8-b505-61157e8a0abf)

When I change it to size (as suggested):

![image](https://github.com/francoismassart/eslint-plugin-tailwindcss/assets/65397328/414cee71-84b5-4985-8cae-17a4d3a28d82)

It recognizes it but doesn't actually work.

I tried updating both tailwind (3.4.1) and eslint-plugin-tailwindcss (3.14.0) and nothing still the same. Even tried with the beta version mentioned above (3.14.1-beta.0).

**Comment by francoismassart** [comment]
Fixed in 3.14.1
