### ISSUE TITLE
[BUG] tabular-nums and slashed-zero are conflicting, but should not.

### ISSUE THREAD

**Issue by einarlove** [francoismassart/eslint-plugin-tailwindcss#316]
**Describe the bug**
Using tabular-nums and slashed-zero gives linting error for conflicting classnames.

**To Reproduce**
Add both `tabular-nums` and `slashed-zero` as classnames to same element with **tailwindcss/no-contradicting-classname** enabled.

**Expected behavior**
It should not give error/warning. The [documentation](https://tailwindcss.com/docs/font-variant-numeric) clearly states they can be combined since it uses css variables under the hood.

**eslint config file or live demo**
"tailwindcss/no-contradicting-classname": "warn"

**Comment by francoismassart** [comment]
@einarlove, indeed some can be combined and some cannot, I made a quick Tailwind Play to document this for later use
https://play.tailwindcss.com/QStyY11EAJ

**Comment by francoismassart** [comment]
I'll close once released 😉

**Comment by francoismassart** [comment]
Please try it via `npm i eslint-plugin-tailwindcss@3.14.2-beta.0 -D` and let me know how it goes. 😉

**Comment by francoismassart** [comment]
@einarlove Please try this beta version:

`npm i eslint-plugin-tailwindcss@3.14.2-beta.1 -D`

and give me feedbacks.

**Comment by francoismassart** [comment]
Fixed in the latest release `eslint-plugin-tailwindcss@3.14.2`
