### ISSUE TITLE
[BUG] changes in tailwind.config.js are not detected

### ISSUE THREAD

**Issue by francoismassart** [francoismassart/eslint-plugin-tailwindcss#36]
**Describe the bug**

Changes made  and saved on `tailwind.config.js` are not recognized by the plugin without restarting ESLint.

> You need to restart ESLint server after saving  for the plugin to recognise the new custom generated classes.

**To Reproduce**

1. Add new config key on `tailwind.config.js`
2. Save `tailwind.config.js`
3. Use a valid classname using the new key
4. The classname will not be detected as a valid classname

**Expected behavior**

The new config should be detected and used by the rules...

**Comment by francoismassart** [comment]
FIXED in `v1.13.3`

**Comment by dalmo3** [comment]
This actually broke config detection for me. I.e. it doesn't detect custom classnames anymore, even after restarting ESLint server.

Going back to 1.13.2 and it works just as before.

**Comment by francoismassart** [comment]
My bad @dalmo3, please try `v1.13.4`
See the details below:
https://github.com/francoismassart/eslint-plugin-tailwindcss/commit/f37924e86a12b720e20baa736677b3a99a1334e9

I forgot the synchronous nature of eslint...

**Comment by dalmo3** [comment]
That seemed to work, thanks Francois!
