### ISSUE TITLE
[Feature request] Support `dark` class

### ISSUE THREAD

**Issue by kripod** [francoismassart/eslint-plugin-tailwindcss#43]
**Is your feature request related to a problem? Please describe.**

When Tailwind’s `darkMode` option [is set to `"class"`](https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually), eslint-plugin-tailwindcss can’t recognize `dark` as a valid class name and emits a warning.

**Describe the solution you'd like**

Not to emit a false-positive `tailwindcss/no-custom-classname` warning when using the `dark` class.

**Comment by francoismassart** [comment]
FIXED in https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v1.14.0

Thank you for reporting the issue 👍
