### ISSUE TITLE
[Feature request] Include `"plugins": ["tailwindcss"]` in the recommended preset

### ISSUE THREAD

**Issue by kripod** [francoismassart/eslint-plugin-tailwindcss#44]
**Is your feature request related to a problem? Please describe.**

When using the recommended preset as suggested [by the readme](https://github.com/francoismassart/eslint-plugin-tailwindcss/tree/ece7948da2d39b2f77038db93b99745640931dd1#configuration), `"plugins": ["tailwindcss"]` isn’t included automatically. This makes it a little cumbersome to consume the recommended configuration without overriding defaults.

**Describe the solution you'd like**

Include `"plugins": ["tailwindcss"]` in `plugin:tailwindcss/recommended`.

**Comment by francoismassart** [comment]
FIXED in https://github.com/francoismassart/eslint-plugin-tailwindcss/releases/tag/v1.14.0

Thank you for reporting the issue 👍

**Comment by Nightliss** [comment]
https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/a5e713b3f9e05f9691f73506fe412130587a82b4/lib/index.js#L21

Hi there @francoismassart, that is a typo - should be `tailwindcss` :) It breaks eslint in current version.

**Comment by francoismassart** [comment]
FIXED in `v1.14.1`, thank you for reporting @Nightliss
