### ISSUE TITLE
[Feature request] Support custom Tailwind configuration

### ISSUE THREAD

**Issue by francoismassart** [francoismassart/eslint-plugin-tailwindcss#5]
**Is your feature request related to a problem? Please describe.**
Some users would like to be able to use the plugin with their own custom Tailwind config diverging from the original/default config provided by Tailwind CSS.
This can be useful if you use different colors, additional breakpoint variants, etc.

**Describe the solution you'd like**
The best solution would be to:

1. Provide the path to the `tailwind.config.js`
2. Parse the configuration
3. Extend/override the plugin configuration

**Comment by francoismassart** [comment]
I started working on this feature few days ago, some regex values of `groups.js` will be adapted. 
It will increase the bundle size as we will need to use `tailwindcss` as a dependency in order to use their `resolveConfig` feature + its default config.

It is not really an issue as this plugin is a devDependency so end user won't have to lose performances.

**Comment by dalmo3** [comment]
Just wanted to point out that you need to restart ESLint server after saving `tailwind.config.js` for the plugin to recognise the new custom generated classes.

Thanks a lot for the wonderful plugin, Francois!

**Comment by francoismassart** [comment]
Hi @dalmo3,
thank you for the feedback, I'll try to fix #36 soon.

**Comment by francoismassart** [comment]
@dalmo3 I just released the fix in `v1.13.3`... Let me know if it works for you 🤔
