### ISSUE TITLE
[Feature request] Change groupByResponsive to true by default

### ISSUE THREAD

**Issue by kawpii** [francoismassart/eslint-plugin-tailwindcss#50]
**Is your feature request related to a problem? Please describe.**

Currently by default plugin order classes according to order where responsive variants are in between different  other classes. But this is not best practice, since TailwindCSS encourage mobile first approach usually non responsive variants classes are applied to mobile and then to the other higher responsive variants if it is not overridden. Mixing responsive variants with other classes make it harder to understand the code.

**Describe the solution you'd like**

Make default `groupByResponsive: true` 

**Describe alternatives you've considered**

Overriding the default in `.eslintrc`

**Additional context**

See read [this comment](https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/30#issuecomment-856608630)

**Comment by kaushalyap** [comment]
Sorry If I bothered you, any way keep up the good work! You go my star!

**Comment by francoismassart** [comment]
@kaushalyap sorry if my response seemed rude, I was not bothered don't worry 😉 
Thank you for your feedback
