### ISSUE TITLE
[BUG] per-side border colors incorrectly showing as invalid

### ISSUE THREAD

**Issue by zslabs** [francoismassart/eslint-plugin-tailwindcss#55]
**Describe the bug**
When attempting to use a valid per-side border color, such as `border-t-current` (added in https://github.com/tailwindlabs/tailwindcss/pull/4404), it is reported this is an invalid class.

**Expected behavior**
Per-side border colors should work as expected.

**Screenshots**
<img width="581" alt="Screen Shot 2021-09-21 at 4 07 51 PM" src="https://user-images.githubusercontent.com/1018402/134240393-49123fe8-7412-4eca-85d6-9efe14a7c7d2.png">

**Environment (please complete the following information):**
 - OS: [e.g. macOS, windows 10]
 - Softwares + version used:
     -  VSCode 1.60.1

**Comment by francoismassart** [comment]
I'll release a new version of the package soon

**Comment by zslabs** [comment]
Appreciate it!
