### ISSUE TITLE
[BUG] Classes added via tailwind.config.js not recognized

### ISSUE THREAD

**Issue by zslabs** [francoismassart/eslint-plugin-tailwindcss#56]
**Describe the bug**
Using the [official docs](https://tailwindcss.com/docs/adding-new-utilities), adding a new class and referencing it in render are not recognized.

**To Reproduce**
1. Use [official docs](https://tailwindcss.com/docs/adding-new-utilities) to add new class
2. Attempt to use new class
3. See error

**Expected behavior**
Custom utilities should be recognized

**Screenshots**

<img width="605" alt="Screen Shot 2021-09-21 at 8 22 23 PM" src="https://user-images.githubusercontent.com/1018402/134264563-13854e66-0a13-4fd9-8ab2-aa98321d6247.png">
The VSCode Intellisense extension does see the class as valid though:
<img width="820" alt="Screen Shot 2021-09-21 at 8 22 13 PM" src="https://user-images.githubusercontent.com/1018402/134264567-c314fb27-413c-4dad-a84c-68630f89c3ac.png">
**Environment (please complete the following information):**

 - OS: [e.g. macOS, windows 10]
 - Softwares + version used:
     -  VSCode 1.60.1

**Comment by zslabs** [comment]
👋 Just wanted to add that I tried requiring in the config file like https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/51 without any luck. I logged-out the config file as it's read inside of where this linter reads in the value and do see it there too.

**Comment by zslabs** [comment]
@francoismassart Thanks for the continued work on this plugin! I saw the recent updates and figured I'd give this another shot, but am unfortunately still unable to use custom classes:
<img width="566" alt="Screen Shot 2022-01-08 at 10 40 58 AM" src="https://user-images.githubusercontent.com/1018402/148650419-8690bd99-58e0-4299-b6df-a0a15c7139e7.png">
<img width="708" alt="Screen Shot 2022-01-08 at 10 41 55 AM" src="https://user-images.githubusercontent.com/1018402/148650429-90d93667-552f-471f-b7f1-0fa58db735ad.png">
Any tips on what I could try? I attempted to use the eslint `settings` object; passing through my config `tailwind.config.js` path via a string and also from a `require()` without any luck.

**Comment by francoismassart** [comment]
Hi @zslabs I don't know yet how to work on this issue as I never used that specific feature...

**Comment by zslabs** [comment]
Hey @francoismassart appreciate the response! Is it the correct assumption that custom classes made within `tailwind.config.js` should be recognized correctly?

I noticed when adding a plugin like https://www.npmjs.com/package/tailwind-gradient-mask-image I was still getting the warning, so I wanted to make sure I understood how classes are parsed from the config. Thanks!

**Comment by francoismassart** [comment]
I did plan to extract all the classnames generated by a plugins but it can become a performance issue because e.g. the official typography plugin can generate more than 238.000 classnames.

For now, please:

- disable the rule on specific line
- or
- add your classnames to the whitelist option

**Comment by zslabs** [comment]
Gotcha, thanks for the explanation and workaround suggestions. Appreciate you making this tool!

**Comment by francoismassart** [comment]
I’ll keep you posted when you can skip the whitelist option for this. 😉
