### ISSUE TITLE
[BUG] Custom classes are not parsed in vite dev mode

### ISSUE THREAD

**Issue by DrJume** [francoismassart/eslint-plugin-tailwindcss#59]
**Describe the bug**
_Project is using vite._ 
Classes defined in the `<style>` section of a Vue SFC are not detected. Using a self defined class, `tailwindcss/no-custom-classname` is still thrown by eslint when using a self defined CSS class inside `<template>`.

**To Reproduce**
1. Clone the demo repo linked below
2. Go to App.vue
3. Run `npm run lint`

The problem goes away after running `npm run build` once. This generates a dist/ directory. After closing and reopening App.vue, no more eslint warning/error is thrown.

Because vite doesn't generate a dist/ folder during dev mode (vue-cli's serve mode), the error persists.
Vite uses `build` to generate the dist/ folder and `serve` for serving the files with a temporary HTTP server.

I suspect, that the problem is connected with the different build system of vite (instead of webpack used by vue-cli).

**Expected behavior**
No eslint warning should be thrown, because we are using a self defined CSS class inside the Vue SFC.

**Environment (please complete the following information):**
https://github.com/DrJume/eslint-plugin-tailwindcss-vite-sfc-issue

**Comment by DrJume** [comment]
I dove a little bit deeper into the problem and found out, that the problem lies with `vite`. I updated the description and provided a demo project repo

**Comment by francoismassart** [comment]
I checked SFC with different parsers in https://astexplorer.net/ but none of the parser can expose the content of the `<style>` section.

Here are few workarounds for your issue:

- Use an external file with the `.css` extension and their classnames should be picked up
- Disable the `no-custom-classname` rule for the SFC `.vue` files
- Provide the list of valid classnames via the `whitelist` option

If you have another solution to expose, please re-open the issue
