### ISSUE TITLE
Extract class-sorting into a utility

### ISSUE THREAD

**Issue by pmeinhardt** [francoismassart/eslint-plugin-tailwindcss#60]
Hi 👋🙂  For a start, thanks for working on this plugin. 💚 

I recently created a [rehype](https://github.com/rehypejs/rehype) plugin to sort Tailwind CSS classes used in HTML documents/templates:
 https://github.com/bitcrowd/rehype-sort-tailwind-classes

In a first iteration, I've gone with [tailwind-classes-sorter](https://github.com/Acidic9/tailwind-classes-sorter) to handle the ordering of classes. I have the impression the project is not all that active though and was wondering whether you'd be open to providing the code responsible for the sorting of class names as a separate utility module (so we could integrate this instead). 🔧 

At the moment, the code for sorting (and de-duplicating…) seems to be nested inside of the `classnames-order` rule, making it somewhat unfeasible to use it on its own. 📦 

Maybe this could be moved into it's own file and made independent of the ESLint AST? 🤔 

I.e. I imagine a class/function interface which you can configure with the same/similar options as the ESLint plugin (path to `tailwind.config.js`, `prependCustom`…) and to which you then simply pass a classname string/array of classes to be sorted.

I'm happy to pitch in and up for discussing further details if you think this is feasible.

Cheers. 🙂

**Comment by francoismassart** [comment]
Hi @pmeinhardt,
sorry for the late response 😅 

While I like the idea, I don't think I'll spend time on extracting the class sorting utility but:

- As this project is in MIT you can reuse parts of it, no question asked.
- Or if you know how to do it, you can fork this project and submit a Pull Request

At the moment, I prefer invest the rare opportunities I have on new rules or migrating the source code in typescript.
