### ISSUE TITLE
[BUG] Newly installed plugin throws CssSyntaxError

### ISSUE THREAD

**Issue by jonnywilliamson** [francoismassart/eslint-plugin-tailwindcss#61]
**Describe the bug**
After following the instructions on this repository, and installing eslint and eslint-plugin-tailwindcss, I get the following error when using my IDE and opening a vue SFC file.

```
CssSyntaxError: Error while loading rule 'tailwindcss/no-custom-classname': <css input>:1:1: Unexpected }
Occurred while linting /Users/jonathan/Code/ialpa/resources/js/Pages/Messages/MessageLogs.vue
    at Input.error (/Users/jonathan/Code/ialpa/node_modules/postcss/lib/input.js:123:16)
    at Parser.unexpectedClose (/Users/jonathan/Code/ialpa/node_modules/postcss/lib/parser.js:522:22)
    at Parser.end (/Users/jonathan/Code/ialpa/node_modules/postcss/lib/parser.js:353:12)
    at Parser.parse (/Users/jonathan/Code/ialpa/node_modules/postcss/lib/parser.js:43:16)
    at Function.parse (/Users/jonathan/Code/ialpa/node_modules/postcss/lib/parse.js:11:12)
    at generateClassnamesListSync (/Users/jonathan/Code/ialpa/node_modules/eslint-plugin-tailwindcss/lib/util/cssFiles.js:29:28)
    at Object.create (/Users/jonathan/Code/ialpa/node_modules/eslint-plugin-tailwindcss/lib/rules/no-custom-classname.js:85:33)
    at createRuleListeners (/Users/jonathan/Code/ialpa/node_modules/eslint/lib/linter/linter.js:765:21)
    at /Users/jonathan/Code/ialpa/node_modules/eslint/lib/linter/linter.js:937:31
    at Array.forEach (<anonymous>)
Process finished with exit code -1
```

If I add the following line to the `rules` section of my `.eslintrc.js` the error goes away.

```js
   "tailwindcss/no-custom-classname": "off",
```

**To Reproduce**
1. Install following the exact steps on the intro to this repo.
2. Enable ESLint in PHPStorm
3. Open a vue file.

**Expected behavior**
No error.

**Screenshots**
![image](https://user-images.githubusercontent.com/2513663/136856042-f29c977c-7a49-4c88-a6b3-002c14f114ce.png)

![image](https://user-images.githubusercontent.com/2513663/136856123-5d5a9fab-abae-4ff8-b871-95ed6912d713.png)

![image](https://user-images.githubusercontent.com/2513663/136856232-173d0187-7787-49db-971f-6fd23a314140.png)

**Environment (please complete the following information):**
 - OS: macOS 10.15.7
 - PHPstorm 2021.2.1
 - Node 16.5.0
 - npm 7.23.0

**Additional context**
The other rules work fine when the no-custom-classname is OFF. Eslint detects problems with tailwind class order etc and fixes them

**Comment by francoismassart** [comment]
This related to the parsing of the CSS files, what is the content of the CSS files parsed by the plugin on your project ?
I guess the problematic file is using the tailwind directives.

A simple solution would be omitting this particular problematic file.
Would you share a dummy project demonstrating the issue ?

**Comment by francoismassart** [comment]
Does it work for you with the proposed solution ? Closing this issue, let me know 😉

**Comment by sebsobseb** [comment]
@francoismassart Had the same issue, but the solution was hard to try, because we don't know which file triggers the problem.
When looking at the errors from @jonnywilliamson, my guess is that it's in a [Laravel](https://laravel.com/) project using [Inertia.js](https://inertiajs.com/), which is the same stack as us. The eslint command executed is `eslint --ext .js,.vue resources/js`. Will try to provide a simple dummy project demonstrating the issue.
