### ISSUE TITLE
[BUG] Class 'aspect-none' from @tailwindcss/aspect-ratio plugin is being treated as not Tailwind CSS class

### ISSUE THREAD

**Issue by leventeszmolka** [francoismassart/eslint-plugin-tailwindcss#63]
**Describe the bug**
Class `aspect-none` from `@tailwindcss/aspect-ratio` plugin is being treated as not a Tailwind CSS class.

**To Reproduce**
1. Add `aspect-none` as CSS class to an element.
2. `eslint-plugin-tailwindcss` will show a warning.

**Expected behavior**
Don't show a warning as this class is valid and part of plugin `@tailwindcss/aspect-ratio`.

**Comment by francoismassart** [comment]
Hi @leventeszmolka, thank you for reporting the issue 👍 

I added a fix in version `1.17.1-beta.1` you should be able to test it out before I release version `1.17.1` by installing the beta version via `npm i eslint-plugin-tailwindcss@beta`

Can you please test it out and confirm that it is resolving your issue ?
Thank you for your feedback
