### ISSUE TITLE
[BUG] path.join(__dirname, "some path") doesn't seem to find the tailwind config file

### ISSUE THREAD

**Issue by AndysonDK** [francoismassart/eslint-plugin-tailwindcss#66]
**Describe the bug**
This doesn't seem to work:
```JavaScript
settings: {
  tailwindcss: {
    config: path.join(__dirname, "packages/web/tailwind.config.js")
  }
}
```

But doing this works:
```JavaScript
settings: {
  tailwindcss: {
    config: "packages/web/tailwind.config.js"
  }
}
```
This works too:
```JavaScript
const tailwindConfig = require("./packages/web/tailwind.config")

settings: {
  tailwindcss: {
    config: tailwindConfig 
  }
}
```

**Expected behavior**
I would like to be consistent with my other ways of specifying files to eslint rules/plugins.
Therefore I would like to specify this and still have the plugin able to find my tailwind config.
```JavaScript
settings: {
  tailwindcss: {
    config: path.join(__dirname, "packages/web/tailwind.config.js")
  }
}
```
**Environment:**
 - OS: [WSL2 (Ubuntu 20.04.3 LTS)]
 - Softwares + version used:
     -  [e.g. VSCode 1.62.2]
     -  [Windows terminal, npm 8.1.2, node v14.17.6]

**Comment by francoismassart** [comment]
Hi @AndysonDK ,
could you share a repository demonstrating the issue with a similar setup, that would help as I don't have a lot of free time at the moment.

Thanks

**Comment by francoismassart** [comment]
The plugin already resolve the path from the current directory, so imagine:

- you're working on `/Users/johndoe/project/`
- if you are using `config: path.join(__dirname, "packages/web/tailwind.config.js")` 
- Then the plugin will try to load the config using the incorrect path `/Users/johndoe/project//Users/johndoe/project/packages/web/tailwind.config.js`

I think I'll test if the provided path is absolute and skip this resolve step if it is.
