### ISSUE TITLE
[BUG] Classname 'focus-visible:ring-offset-orange-300' is not a Tailwind CSS class!

### ISSUE THREAD

**Issue by chillitom** [francoismassart/eslint-plugin-tailwindcss#70]
**Describe the bug**
With the upgrade to Tailwind 3 the linter complains that a class name doesn't exist when it does.

**To Reproduce**
In a tailwind 3 project assign the classname `focus-visible:ring-offset-orange-300`

**Expected behavior**
No warning should be generated.

**Comment by francoismassart** [comment]
Hi, you are using new features of TailwindCSS v3.

The latest version of the plugin does not support TailwindCSS v3 **yet**.

Next major release will only works with TailwindCSS v3.

**Comment by francoismassart** [comment]
Related issue: ➡️  #69

**Comment by francoismassart** [comment]
Please try using version 3.0.0 of the plugin which supports TailwindCSS v3

**Comment by chillitom** [comment]
works great, thank you!
