### ISSUE TITLE
Svelte support

### ISSUE THREAD

**Issue by gustavopch** [francoismassart/eslint-plugin-tailwindcss#72]
I have a repo using both React and Svelte. I was able to make this plugin work with React, but not with Svelte. I'm just declaring the plugin and extending from the recommended rules. Of course, ESLint is properly configured for Svelte; it's just this plugin that doesn't work.

It detects this error in React:
```js
export const Foo = () => {
  return <div className="p-2 p-4" />
}
```

But not this error in Svelte:
```svelte
<div class="p-8 p-2" />
```

I see that Vue is supported (there are tests for it), so I guess it shouldn't be much hard to also support Svelte. Or maybe it's already supported and there's something else that must be added to the config?

**Repro:** https://github.com/gustavopch/repro-eslint-plugin-tailwindcss

P.S.: not sure if this is a bug or a feature request TBH.

**Comment by francoismassart** [comment]
Hi @gustavopch,
I'm not familiar with Svelte and I'm currently focusing on upgrading the plugin for TailwindCSS v3, so I won't be able to work on this right away.

Feel free to contribute if you have some expertize. 😉

**Comment by francoismassart** [comment]
See my PR https://github.com/gustavopch/repro-eslint-plugin-tailwindcss/pull/1

**Comment by scorsi** [comment]
@francoismassart 
It's not resolved, your proposition is like parsing typescript file as javascript files... We can't change the parser/processor of svelte files :) 
Do you think you can look at this sometime ?

**Comment by polyzen** [comment]
https://github.com/francoismassart/eslint-plugin-tailwindcss/issues/214#issuecomment-1436661883

**Comment by polyzen** [comment]
Might be worth pointing out https://github.com/sveltejs/eslint-plugin-svelte is the new default plugin.

**Comment by floriandotorg** [comment]
Hey everyone, may I ask why this one was closed? The plugin still doesn't support Svelte, does it?

**Comment by nekochan0122** [comment]
Hello @francoismassart, can u re-open this?
The plugin is not support Svelte yet.
