### ISSUE TITLE
Support for: escaped characters (eg. slash, dot) in classes, custom bracket notation

### ISSUE THREAD

**Issue by finnmerlett** [francoismassart/eslint-plugin-tailwindcss#73]
**Is your feature request related to a problem? Please describe.**
Using tailwind's custom property value syntax (square brackets) results in an error. The same goes for when you want to use full-stops or slashes in classnames - they aren't pulled correctly from the css file into the list of supported names.

**Describe the solution you'd like**
Support for the above missing features

**Describe alternatives you've considered**
For the escaped characters, the only solution is to avoid using them which is annoying. For the custom syntax a generic whitelist matcher could be put in the error config, but this would not be clear which properties support this and would also not check the tailwind class before the square brackets

**Comment by francoismassart** [comment]
@finnmerlett Could you provide example classnames for each cases you are experiencing please ?
Thanks

**Comment by francoismassart** [comment]
You can use v2.0.1 or v3.3.1

**Comment by francoismassart** [comment]
@finnmerlett no, actually, there was an issue with special characters 😉 
Thank you for reporting it
