### ISSUE TITLE
[BUG] Important marker throws warning on flex and hidden displays but not on block

### ISSUE THREAD

**Issue by ismailToyran** [francoismassart/eslint-plugin-tailwindcss#82]
**Describe the bug**
It seems like display category triggers warning with `!important`. Seems to be working on widths paddings and many more. Strange it's working with `block` as well. Right now I've only faced this issue with `flex` and `hidden`, didn't try others though. Working but throwing warning.

**To Reproduce**
1. Add important marker `!` before `flex` and `hidden`
2. You'll get the warning

**Expected behavior**
There should be no warning.

**Screenshots**

`!hidden`
![image](https://user-images.githubusercontent.com/33982052/147638120-674f7f04-0ad9-4afc-b101-047a7c1a64b4.png)

`lg:!flex`
![image](https://user-images.githubusercontent.com/33982052/147638057-a31049f0-2987-40d7-9cf2-88a233fc6003.png)

**Environment (please complete the following information):**
OS: **Windows 10**
Softwares + version used:
- **VSCode: 1.63.2**
- **eslint-plugin-tailwindcss: 3.0.0**
- **tailwindcss: 3.0.7**

**Comment by Serator** [comment]
This is also reproduced in my code with all `!display` (https://tailwindcss.com/docs/display) properties except `!block`.

* OS: Windows 10
* Softwares + version used:
  * VSCode: 1.63.2
  * @typescript-eslint/parser: 5.6.0
  * eslint: 8.4.1
  * eslint-plugin-tailwindcss: 3.0.1
  * tailwindcss: 3.0.8

**Comment by francoismassart** [comment]
I’ll take a look at it tonight

**Comment by francoismassart** [comment]
Fixed, thank you for the feedback @ismailToyran & @Serator, it'll be shipped in `3.0.2`
