### ISSUE TITLE
[BUG]  Boolean values in class throws error.

### ISSUE THREAD

**Issue by ApproachingApathy** [francoismassart/eslint-plugin-tailwindcss#83]
**Describe the bug**
If there is a boolean in the class attribute, `getClassNamesFromAttribute` throws an unhandled TypeError.
```
TypeError: attrVal.replace is not a function
```

**To Reproduce**
1. Include a boolean value in a className attribute.
2. Lint the file.

**Expected behavior**
The linter should not break in this case.

**Environment (please complete the following information):**
 - OS: linux
 - Softwares + version used:
     - VSCode 1.62.2
     - ESLint 7.24.0
     - Node 14.18.1

**Additional context**
In my project we have a utility to conditionally construct classNames. If a falsy value is passed into the function, the function will exclude the segment from the resulting string.  `getClassNamesFromAttribute` causes a crash on the following code. 

```jsx
<button
    type="button"
    className={classnames(
         "xl p-2 font-medium",
         boolVal ? false : "text-black-light2"
    )}
/>
```

I was able to get the linter to run by changing this:
```js
function getClassNamesFromAttribute(attrVal, trim = true) {
    let classNames = [];
    if (attrVal === undefined || attrVal === null || attrVal.length === 0) {
        return classNames;
    }
// ...
}
```

to this: 
```js
function getClassNamesFromAttribute(attrVal, trim = true) {
    let classNames = [];
    if (typeof attrVal !== "string" || attrVal.length === 0) {
        return classNames;
    }
// ...
}
```

**Comment by francoismassart** [comment]
Thank you for reporting the issue @ApproachingApathy, it'll be fixed in `3.0.2`
