### ISSUE TITLE
[BUG] `snap-x` and `snap-mandatory` are conflicting classes

### ISSUE THREAD

**Issue by muqshots** [francoismassart/eslint-plugin-tailwindcss#90]
**Describe the bug**
snap-x snap-mandatory are detected as conflicting classes

**To Reproduce**
Use snap-x snap-mandatory together

**Expected behavior**
They should not conflict, They're even used together in the tailwindcss.com examples
https://tailwindcss.com/docs/scroll-snap-type

**Comment by francoismassart** [comment]
Hi @muqshots
thank you for reporting the issue, I just published `3.1.1` which fixes the issue.
