### ISSUE TITLE
[BUG] "transform" suggested for removal when still actively used

### ISSUE THREAD

**Issue by chillitom** [francoismassart/eslint-plugin-tailwindcss#96]
**Describe the bug**
With Tailwind v3 the linter suggests removing "transform" class name entries however this is still needed in many case, for example the Tailwind UI examples themselves use this in their modal dialogs example code. Maybe there are better alternative classes to use instead but the linter only suggest to remove it.

**To Reproduce**
Include the transform class on an element, the linter will simply suggest removing it.

**Expected behavior**
The transform class name should be replaced with a equivalent functionality, not simply removed.

**Environment (please complete the following information):**
    "eslint-plugin-tailwindcss": "^3.2.0",
    "tailwindcss": "^3.0.13",

**Comment by francoismassart** [comment]
Hi there @chillitom 

Could you provide me a snippet of html where the `transform` class is indeed mandatory.
From what I understood in TW3 docs, transform is not needed anymore:
https://tailwindcss.com/docs/upgrade-guide#automatic-transforms-and-filters

Here is a simple example demonstrating that transform is not required in TW3:
https://play.tailwindcss.com/q9UMwwYx3v

Thank you for your feedback

**Comment by thebuilder** [comment]
That's a bug in Tailwind UI - The `transform` just causes the modal to be placed on top of the `position: absolute;` backdrop. You can replace it with `relative` or `z-index-0`.

**Comment by chillitom** [comment]
Thanks, using `relative` worked for me.  Great plugin, thanks for all the hard work!
