### ISSUE TITLE
[BUG] tailwind plugin prose not supported

### ISSUE THREAD

**Issue by dmtrKovalenko** [francoismassart/eslint-plugin-tailwindcss#97]
**Describe the bug**
When applied 2 classes from @tailwindcss/typography like `prose-red prose-xl` error `tailwindcss/no-contradicting-classname` throws 

**To Reproduce**
1. Add tailwind plugin https://tailwindcss.com/docs/typography-plugin
1. Apply class `prose-red prose-xl`
2. Observe error

**Expected behavior**
No error

 
**eslint config file or live demo**
![image](https://user-images.githubusercontent.com/16926049/149547188-9a34e086-6d65-49ea-9ed2-eb72e4be40f7.png)

**Comment by francoismassart** [comment]
Hi @dmtrKovalenko, indeed the plugin has been updated and at the moment the classnames from the official plugins are not generated dynamically but I'm working on it. I'll keep you posted.

**Comment by francoismassart** [comment]
Hi @dmtrKovalenko, please give a try to this beta version:

`npm i -D eslint-plugin-tailwindcss@3.5.1-beta.0`

**Comment by francoismassart** [comment]
I just published a beta version with the fixes listed on #132 
https://github.com/francoismassart/eslint-plugin-tailwindcss/tree/fix/no-custom-classname-plugin-support#readme

`npm i eslint-plugin-tailwindcss@3.6.0-beta.0`

Please give it a try and provide feedback and or issues 👍 
Thank you

**Comment by francoismassart** [comment]
@dmtrKovalenko when you get a chance please try the latest beta and give me feedback about your issue.
